echoSql: False
rootPath: /api/book-service
databaseUri: sqlite:////app/data/books.db

# Should get these from a secret store, these are just base64...
db:
  username: Ym9vay1kYi11c2VyCg==
  password: YWJjMTIzIQo=

apm:
  enabled: "true"
  serverUrl: "https://elk-dev.k8s.onintranet.com:8200"
  verifyServerCert: "false"
  log:
    ecsFormatting: "off"
    file: "demo-book-service.log"
    fileSize: "16mb"
    level: "info"
    recording: "true"

service:
  type: ClusterIP
  port: 80
